/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl2;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.xtext.example.mydsl2.AbstractMyDslRuntimeModule;
import org.xtext.example.mydsl2.MyDslImportUriGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
  @Override
  public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
    return MyDslImportUriGlobalScopeProvider.class;
  }
}
