/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl2.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ExtensionInclusionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.ExtensionInclusion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMultipleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cMultipleMultipleKeyword_0_0 = (Keyword)cMultipleAssignment_0.eContents().get(0);
		private final Keyword cExtensionInclusionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEStringParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNameEStringParserRuleCall_5_0 = (RuleCall)cNameAssignment_5.eContents().get(0);
		private final Keyword cDescriptionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDescriptionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDescriptionEStringParserRuleCall_7_0 = (RuleCall)cDescriptionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPointCutKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cPointCutAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cPointCutPointCutParserRuleCall_8_2_0 = (RuleCall)cPointCutAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cPointCutAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cPointCutPointCutParserRuleCall_8_3_1_0 = (RuleCall)cPointCutAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAdviceKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cAdviceAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cAdviceAdviceParserRuleCall_9_2_0 = (RuleCall)cAdviceAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cAdviceAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cAdviceAdviceParserRuleCall_9_3_1_0 = (RuleCall)cAdviceAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		////import "http://www.xtext.org/example/mydsl1/TestDsl"
		//ExtensionInclusion featureSolution::ExtensionInclusion:
		//	multiple?='multiple'?
		//	'ExtensionInclusion'
		//	id=EString
		//	'{'
		//	'name' name=EString
		//	'description' description=EString ('pointCut' '{' pointCut+=PointCut ("," pointCut+=PointCut)* '}')? ('advice' '{'
		//	advice+=Advice ("," advice+=Advice)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//multiple?='multiple'? 'ExtensionInclusion' id=EString '{' 'name' name=EString 'description' description=EString
		//('pointCut' '{' pointCut+=PointCut ("," pointCut+=PointCut)* '}')? ('advice' '{' advice+=Advice ("," advice+=Advice)*
		//'}')? '}'
		public Group getGroup() { return cGroup; }
		
		//multiple?='multiple'?
		public Assignment getMultipleAssignment_0() { return cMultipleAssignment_0; }
		
		//'multiple'
		public Keyword getMultipleMultipleKeyword_0_0() { return cMultipleMultipleKeyword_0_0; }
		
		//'ExtensionInclusion'
		public Keyword getExtensionInclusionKeyword_1() { return cExtensionInclusionKeyword_1; }
		
		//id=EString
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_2_0() { return cIdEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//name=EString
		public Assignment getNameAssignment_5() { return cNameAssignment_5; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_5_0() { return cNameEStringParserRuleCall_5_0; }
		
		//'description'
		public Keyword getDescriptionKeyword_6() { return cDescriptionKeyword_6; }
		
		//description=EString
		public Assignment getDescriptionAssignment_7() { return cDescriptionAssignment_7; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_7_0() { return cDescriptionEStringParserRuleCall_7_0; }
		
		//('pointCut' '{' pointCut+=PointCut ("," pointCut+=PointCut)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'pointCut'
		public Keyword getPointCutKeyword_8_0() { return cPointCutKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//pointCut+=PointCut
		public Assignment getPointCutAssignment_8_2() { return cPointCutAssignment_8_2; }
		
		//PointCut
		public RuleCall getPointCutPointCutParserRuleCall_8_2_0() { return cPointCutPointCutParserRuleCall_8_2_0; }
		
		//("," pointCut+=PointCut)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//pointCut+=PointCut
		public Assignment getPointCutAssignment_8_3_1() { return cPointCutAssignment_8_3_1; }
		
		//PointCut
		public RuleCall getPointCutPointCutParserRuleCall_8_3_1_0() { return cPointCutPointCutParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('advice' '{' advice+=Advice ("," advice+=Advice)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'advice'
		public Keyword getAdviceKeyword_9_0() { return cAdviceKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//advice+=Advice
		public Assignment getAdviceAssignment_9_2() { return cAdviceAssignment_9_2; }
		
		//Advice
		public RuleCall getAdviceAdviceParserRuleCall_9_2_0() { return cAdviceAdviceParserRuleCall_9_2_0; }
		
		//("," advice+=Advice)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//advice+=Advice
		public Assignment getAdviceAssignment_9_3_1() { return cAdviceAssignment_9_3_1; }
		
		//Advice
		public RuleCall getAdviceAdviceParserRuleCall_9_3_1_0() { return cAdviceAdviceParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class PlacementStrategyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.PlacementStrategy");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPlacementStrategy_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExternalCallPlacementStrategyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInternalActionPlacementStrategyParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cControlFlowPlacementStrategyParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//PlacementStrategy featureSolution::PlacementStrategy:
		//	PlacementStrategy_Impl | ExternalCallPlacementStrategy | InternalActionPlacementStrategy |
		//	ControlFlowPlacementStrategy;
		@Override public ParserRule getRule() { return rule; }
		
		//PlacementStrategy_Impl | ExternalCallPlacementStrategy | InternalActionPlacementStrategy | ControlFlowPlacementStrategy
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PlacementStrategy_Impl
		public RuleCall getPlacementStrategy_ImplParserRuleCall_0() { return cPlacementStrategy_ImplParserRuleCall_0; }
		
		//ExternalCallPlacementStrategy
		public RuleCall getExternalCallPlacementStrategyParserRuleCall_1() { return cExternalCallPlacementStrategyParserRuleCall_1; }
		
		//InternalActionPlacementStrategy
		public RuleCall getInternalActionPlacementStrategyParserRuleCall_2() { return cInternalActionPlacementStrategyParserRuleCall_2; }
		
		//ControlFlowPlacementStrategy
		public RuleCall getControlFlowPlacementStrategyParserRuleCall_3() { return cControlFlowPlacementStrategyParserRuleCall_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class PointCutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.PointCut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPointCutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEntityNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEntityNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEntityNameEStringParserRuleCall_3_0 = (RuleCall)cEntityNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPlacementStrategyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPlacementStrategyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPlacementStrategyPlacementStrategyParserRuleCall_4_1_0 = (RuleCall)cPlacementStrategyAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//PointCut featureSolution::PointCut:
		//	'PointCut'
		//	'{'
		//	'entityName' entityName=EString ('placementStrategy' placementStrategy=PlacementStrategy)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'PointCut' '{' 'entityName' entityName=EString ('placementStrategy' placementStrategy=PlacementStrategy)? '}'
		public Group getGroup() { return cGroup; }
		
		//'PointCut'
		public Keyword getPointCutKeyword_0() { return cPointCutKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'entityName'
		public Keyword getEntityNameKeyword_2() { return cEntityNameKeyword_2; }
		
		//entityName=EString
		public Assignment getEntityNameAssignment_3() { return cEntityNameAssignment_3; }
		
		//EString
		public RuleCall getEntityNameEStringParserRuleCall_3_0() { return cEntityNameEStringParserRuleCall_3_0; }
		
		//('placementStrategy' placementStrategy=PlacementStrategy)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'placementStrategy'
		public Keyword getPlacementStrategyKeyword_4_0() { return cPlacementStrategyKeyword_4_0; }
		
		//placementStrategy=PlacementStrategy
		public Assignment getPlacementStrategyAssignment_4_1() { return cPlacementStrategyAssignment_4_1; }
		
		//PlacementStrategy
		public RuleCall getPlacementStrategyPlacementStrategyParserRuleCall_4_1_0() { return cPlacementStrategyPlacementStrategyParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class AdviceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.Advice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAdviceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEntityNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEntityNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEntityNameEStringParserRuleCall_3_0 = (RuleCall)cEntityNameAssignment_3.eContents().get(0);
		private final Keyword cAppearsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAppearsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAppearsAppearanceEnumRuleCall_5_0 = (RuleCall)cAppearsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPointCutKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPointCutAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cPointCutPointCutCrossReference_6_1_0 = (CrossReference)cPointCutAssignment_6_1.eContents().get(0);
		private final RuleCall cPointCutPointCutEStringParserRuleCall_6_1_0_1 = (RuleCall)cPointCutPointCutCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCompletionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCompletionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cCompletionComplementumVisnetisCrossReference_7_1_0 = (CrossReference)cCompletionAssignment_7_1.eContents().get(0);
		private final RuleCall cCompletionComplementumVisnetisEStringParserRuleCall_7_1_0_1 = (RuleCall)cCompletionComplementumVisnetisCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Advice featureSolution::Advice:
		//	'Advice'
		//	'{'
		//	'entityName' entityName=EString
		//	'appears' appears=Appearance ('pointCut' pointCut=[featureSolution::PointCut|EString])? ('Completion'
		//	Completion=[ComplementumVisnetis|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Advice' '{' 'entityName' entityName=EString 'appears' appears=Appearance ('pointCut'
		//pointCut=[featureSolution::PointCut|EString])? ('Completion' Completion=[ComplementumVisnetis|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//'Advice'
		public Keyword getAdviceKeyword_0() { return cAdviceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'entityName'
		public Keyword getEntityNameKeyword_2() { return cEntityNameKeyword_2; }
		
		//entityName=EString
		public Assignment getEntityNameAssignment_3() { return cEntityNameAssignment_3; }
		
		//EString
		public RuleCall getEntityNameEStringParserRuleCall_3_0() { return cEntityNameEStringParserRuleCall_3_0; }
		
		//'appears'
		public Keyword getAppearsKeyword_4() { return cAppearsKeyword_4; }
		
		//appears=Appearance
		public Assignment getAppearsAssignment_5() { return cAppearsAssignment_5; }
		
		//Appearance
		public RuleCall getAppearsAppearanceEnumRuleCall_5_0() { return cAppearsAppearanceEnumRuleCall_5_0; }
		
		//('pointCut' pointCut=[featureSolution::PointCut|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'pointCut'
		public Keyword getPointCutKeyword_6_0() { return cPointCutKeyword_6_0; }
		
		//pointCut=[featureSolution::PointCut|EString]
		public Assignment getPointCutAssignment_6_1() { return cPointCutAssignment_6_1; }
		
		//[featureSolution::PointCut|EString]
		public CrossReference getPointCutPointCutCrossReference_6_1_0() { return cPointCutPointCutCrossReference_6_1_0; }
		
		//EString
		public RuleCall getPointCutPointCutEStringParserRuleCall_6_1_0_1() { return cPointCutPointCutEStringParserRuleCall_6_1_0_1; }
		
		//('Completion' Completion=[ComplementumVisnetis|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'Completion'
		public Keyword getCompletionKeyword_7_0() { return cCompletionKeyword_7_0; }
		
		//Completion=[ComplementumVisnetis|EString]
		public Assignment getCompletionAssignment_7_1() { return cCompletionAssignment_7_1; }
		
		//[ComplementumVisnetis|EString]
		public CrossReference getCompletionComplementumVisnetisCrossReference_7_1_0() { return cCompletionComplementumVisnetisCrossReference_7_1_0; }
		
		//EString
		public RuleCall getCompletionComplementumVisnetisEStringParserRuleCall_7_1_0_1() { return cCompletionComplementumVisnetisEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class PlacementStrategy_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.PlacementStrategy_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPlacementStrategyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPlacementStrategyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//PlacementStrategy_Impl featureSolution::PlacementStrategy:
		//	{featureSolution::PlacementStrategy}
		//	'PlacementStrategy';
		@Override public ParserRule getRule() { return rule; }
		
		//{featureSolution::PlacementStrategy} 'PlacementStrategy'
		public Group getGroup() { return cGroup; }
		
		//{featureSolution::PlacementStrategy}
		public Action getPlacementStrategyAction_0() { return cPlacementStrategyAction_0; }
		
		//'PlacementStrategy'
		public Keyword getPlacementStrategyKeyword_1() { return cPlacementStrategyKeyword_1; }
	}
	public class ExternalCallPlacementStrategyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.ExternalCallPlacementStrategy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExternalCallPlacementStrategyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExternalCallPlacementStrategyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cMatchingSignatureKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMatchingSignatureAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cMatchingSignatureSignatureCrossReference_3_1_0 = (CrossReference)cMatchingSignatureAssignment_3_1.eContents().get(0);
		private final RuleCall cMatchingSignatureSignatureEStringParserRuleCall_3_1_0_1 = (RuleCall)cMatchingSignatureSignatureCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ExternalCallPlacementStrategy featureSolution::ExternalCallPlacementStrategy:
		//	{featureSolution::ExternalCallPlacementStrategy}
		//	'ExternalCallPlacementStrategy'
		//	'{' ('matchingSignature' matchingSignature=[repository::Signature|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{featureSolution::ExternalCallPlacementStrategy} 'ExternalCallPlacementStrategy' '{' ('matchingSignature'
		//matchingSignature=[repository::Signature|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{featureSolution::ExternalCallPlacementStrategy}
		public Action getExternalCallPlacementStrategyAction_0() { return cExternalCallPlacementStrategyAction_0; }
		
		//'ExternalCallPlacementStrategy'
		public Keyword getExternalCallPlacementStrategyKeyword_1() { return cExternalCallPlacementStrategyKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('matchingSignature' matchingSignature=[repository::Signature|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'matchingSignature'
		public Keyword getMatchingSignatureKeyword_3_0() { return cMatchingSignatureKeyword_3_0; }
		
		//matchingSignature=[repository::Signature|EString]
		public Assignment getMatchingSignatureAssignment_3_1() { return cMatchingSignatureAssignment_3_1; }
		
		//[repository::Signature|EString]
		public CrossReference getMatchingSignatureSignatureCrossReference_3_1_0() { return cMatchingSignatureSignatureCrossReference_3_1_0; }
		
		//EString
		public RuleCall getMatchingSignatureSignatureEStringParserRuleCall_3_1_0_1() { return cMatchingSignatureSignatureEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FQNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.FQN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//FQN:
		//	ID ("." ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ("." ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class InternalActionPlacementStrategyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.InternalActionPlacementStrategy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInternalActionPlacementStrategyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInternalActionPlacementStrategyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cForAllInternalActionsInKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cForAllInternalActionsInAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cForAllInternalActionsInRepositoryComponentCrossReference_3_1_0 = (CrossReference)cForAllInternalActionsInAssignment_3_1.eContents().get(0);
		private final RuleCall cForAllInternalActionsInRepositoryComponentEStringParserRuleCall_3_1_0_1 = (RuleCall)cForAllInternalActionsInRepositoryComponentCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//InternalActionPlacementStrategy featureSolution::InternalActionPlacementStrategy:
		//	{featureSolution::InternalActionPlacementStrategy}
		//	'InternalActionPlacementStrategy'
		//	'{' ('forAllInternalActionsIn' forAllInternalActionsIn=[repository::RepositoryComponent|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{featureSolution::InternalActionPlacementStrategy} 'InternalActionPlacementStrategy' '{' ('forAllInternalActionsIn'
		//forAllInternalActionsIn=[repository::RepositoryComponent|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{featureSolution::InternalActionPlacementStrategy}
		public Action getInternalActionPlacementStrategyAction_0() { return cInternalActionPlacementStrategyAction_0; }
		
		//'InternalActionPlacementStrategy'
		public Keyword getInternalActionPlacementStrategyKeyword_1() { return cInternalActionPlacementStrategyKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('forAllInternalActionsIn' forAllInternalActionsIn=[repository::RepositoryComponent|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'forAllInternalActionsIn'
		public Keyword getForAllInternalActionsInKeyword_3_0() { return cForAllInternalActionsInKeyword_3_0; }
		
		//forAllInternalActionsIn=[repository::RepositoryComponent|EString]
		public Assignment getForAllInternalActionsInAssignment_3_1() { return cForAllInternalActionsInAssignment_3_1; }
		
		//[repository::RepositoryComponent|EString]
		public CrossReference getForAllInternalActionsInRepositoryComponentCrossReference_3_1_0() { return cForAllInternalActionsInRepositoryComponentCrossReference_3_1_0; }
		
		//EString
		public RuleCall getForAllInternalActionsInRepositoryComponentEStringParserRuleCall_3_1_0_1() { return cForAllInternalActionsInRepositoryComponentEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ControlFlowPlacementStrategyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.ControlFlowPlacementStrategy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cControlFlowPlacementStrategyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cControlFlowPlacementStrategyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cForAllControlFlowsInKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cForAllControlFlowsInAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cForAllControlFlowsInRepositoryComponentCrossReference_3_1_0 = (CrossReference)cForAllControlFlowsInAssignment_3_1.eContents().get(0);
		private final RuleCall cForAllControlFlowsInRepositoryComponentEStringParserRuleCall_3_1_0_1 = (RuleCall)cForAllControlFlowsInRepositoryComponentCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ControlFlowPlacementStrategy featureSolution::ControlFlowPlacementStrategy:
		//	{featureSolution::ControlFlowPlacementStrategy}
		//	'ControlFlowPlacementStrategy'
		//	'{' ('forAllControlFlowsIn' forAllControlFlowsIn=[repository::RepositoryComponent|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{featureSolution::ControlFlowPlacementStrategy} 'ControlFlowPlacementStrategy' '{' ('forAllControlFlowsIn'
		//forAllControlFlowsIn=[repository::RepositoryComponent|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{featureSolution::ControlFlowPlacementStrategy}
		public Action getControlFlowPlacementStrategyAction_0() { return cControlFlowPlacementStrategyAction_0; }
		
		//'ControlFlowPlacementStrategy'
		public Keyword getControlFlowPlacementStrategyKeyword_1() { return cControlFlowPlacementStrategyKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('forAllControlFlowsIn' forAllControlFlowsIn=[repository::RepositoryComponent|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'forAllControlFlowsIn'
		public Keyword getForAllControlFlowsInKeyword_3_0() { return cForAllControlFlowsInKeyword_3_0; }
		
		//forAllControlFlowsIn=[repository::RepositoryComponent|EString]
		public Assignment getForAllControlFlowsInAssignment_3_1() { return cForAllControlFlowsInAssignment_3_1; }
		
		//[repository::RepositoryComponent|EString]
		public CrossReference getForAllControlFlowsInRepositoryComponentCrossReference_3_1_0() { return cForAllControlFlowsInRepositoryComponentCrossReference_3_1_0; }
		
		//EString
		public RuleCall getForAllControlFlowsInRepositoryComponentEStringParserRuleCall_3_1_0_1() { return cForAllControlFlowsInRepositoryComponentEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class AppearanceElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl2.MyDsl.Appearance");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBEFOREEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBEFOREBEFOREKeyword_0_0 = (Keyword)cBEFOREEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAFTEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAFTERAFTERKeyword_1_0 = (Keyword)cAFTEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAROUNDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAROUNDAROUNDKeyword_2_0 = (Keyword)cAROUNDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Appearance returns featureSolution::Appearance:
		//	BEFORE | AFTER | AROUND;
		public EnumRule getRule() { return rule; }
		
		//BEFORE | AFTER | AROUND
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BEFORE
		public EnumLiteralDeclaration getBEFOREEnumLiteralDeclaration_0() { return cBEFOREEnumLiteralDeclaration_0; }
		
		//'BEFORE'
		public Keyword getBEFOREBEFOREKeyword_0_0() { return cBEFOREBEFOREKeyword_0_0; }
		
		//AFTER
		public EnumLiteralDeclaration getAFTEREnumLiteralDeclaration_1() { return cAFTEREnumLiteralDeclaration_1; }
		
		//'AFTER'
		public Keyword getAFTERAFTERKeyword_1_0() { return cAFTERAFTERKeyword_1_0; }
		
		//AROUND
		public EnumLiteralDeclaration getAROUNDEnumLiteralDeclaration_2() { return cAROUNDEnumLiteralDeclaration_2; }
		
		//'AROUND'
		public Keyword getAROUNDAROUNDKeyword_2_0() { return cAROUNDAROUNDKeyword_2_0; }
	}
	
	private final ExtensionInclusionElements pExtensionInclusion;
	private final PlacementStrategyElements pPlacementStrategy;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final PointCutElements pPointCut;
	private final AdviceElements pAdvice;
	private final PlacementStrategy_ImplElements pPlacementStrategy_Impl;
	private final ExternalCallPlacementStrategyElements pExternalCallPlacementStrategy;
	private final FQNElements pFQN;
	private final InternalActionPlacementStrategyElements pInternalActionPlacementStrategy;
	private final ControlFlowPlacementStrategyElements pControlFlowPlacementStrategy;
	private final AppearanceElements eAppearance;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pExtensionInclusion = new ExtensionInclusionElements();
		this.pPlacementStrategy = new PlacementStrategyElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.pPointCut = new PointCutElements();
		this.pAdvice = new AdviceElements();
		this.pPlacementStrategy_Impl = new PlacementStrategy_ImplElements();
		this.pExternalCallPlacementStrategy = new ExternalCallPlacementStrategyElements();
		this.pFQN = new FQNElements();
		this.pInternalActionPlacementStrategy = new InternalActionPlacementStrategyElements();
		this.pControlFlowPlacementStrategy = new ControlFlowPlacementStrategyElements();
		this.eAppearance = new AppearanceElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl2.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////import "http://www.xtext.org/example/mydsl1/TestDsl"
	//ExtensionInclusion featureSolution::ExtensionInclusion:
	//	multiple?='multiple'?
	//	'ExtensionInclusion'
	//	id=EString
	//	'{'
	//	'name' name=EString
	//	'description' description=EString ('pointCut' '{' pointCut+=PointCut ("," pointCut+=PointCut)* '}')? ('advice' '{'
	//	advice+=Advice ("," advice+=Advice)* '}')?
	//	'}';
	public ExtensionInclusionElements getExtensionInclusionAccess() {
		return pExtensionInclusion;
	}
	
	public ParserRule getExtensionInclusionRule() {
		return getExtensionInclusionAccess().getRule();
	}
	
	//PlacementStrategy featureSolution::PlacementStrategy:
	//	PlacementStrategy_Impl | ExternalCallPlacementStrategy | InternalActionPlacementStrategy |
	//	ControlFlowPlacementStrategy;
	public PlacementStrategyElements getPlacementStrategyAccess() {
		return pPlacementStrategy;
	}
	
	public ParserRule getPlacementStrategyRule() {
		return getPlacementStrategyAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//PointCut featureSolution::PointCut:
	//	'PointCut'
	//	'{'
	//	'entityName' entityName=EString ('placementStrategy' placementStrategy=PlacementStrategy)?
	//	'}';
	public PointCutElements getPointCutAccess() {
		return pPointCut;
	}
	
	public ParserRule getPointCutRule() {
		return getPointCutAccess().getRule();
	}
	
	//Advice featureSolution::Advice:
	//	'Advice'
	//	'{'
	//	'entityName' entityName=EString
	//	'appears' appears=Appearance ('pointCut' pointCut=[featureSolution::PointCut|EString])? ('Completion'
	//	Completion=[ComplementumVisnetis|EString])?
	//	'}';
	public AdviceElements getAdviceAccess() {
		return pAdvice;
	}
	
	public ParserRule getAdviceRule() {
		return getAdviceAccess().getRule();
	}
	
	//PlacementStrategy_Impl featureSolution::PlacementStrategy:
	//	{featureSolution::PlacementStrategy}
	//	'PlacementStrategy';
	public PlacementStrategy_ImplElements getPlacementStrategy_ImplAccess() {
		return pPlacementStrategy_Impl;
	}
	
	public ParserRule getPlacementStrategy_ImplRule() {
		return getPlacementStrategy_ImplAccess().getRule();
	}
	
	//ExternalCallPlacementStrategy featureSolution::ExternalCallPlacementStrategy:
	//	{featureSolution::ExternalCallPlacementStrategy}
	//	'ExternalCallPlacementStrategy'
	//	'{' ('matchingSignature' matchingSignature=[repository::Signature|EString])?
	//	'}';
	public ExternalCallPlacementStrategyElements getExternalCallPlacementStrategyAccess() {
		return pExternalCallPlacementStrategy;
	}
	
	public ParserRule getExternalCallPlacementStrategyRule() {
		return getExternalCallPlacementStrategyAccess().getRule();
	}
	
	//FQN:
	//	ID ("." ID)*;
	public FQNElements getFQNAccess() {
		return pFQN;
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}
	
	//InternalActionPlacementStrategy featureSolution::InternalActionPlacementStrategy:
	//	{featureSolution::InternalActionPlacementStrategy}
	//	'InternalActionPlacementStrategy'
	//	'{' ('forAllInternalActionsIn' forAllInternalActionsIn=[repository::RepositoryComponent|EString])?
	//	'}';
	public InternalActionPlacementStrategyElements getInternalActionPlacementStrategyAccess() {
		return pInternalActionPlacementStrategy;
	}
	
	public ParserRule getInternalActionPlacementStrategyRule() {
		return getInternalActionPlacementStrategyAccess().getRule();
	}
	
	//ControlFlowPlacementStrategy featureSolution::ControlFlowPlacementStrategy:
	//	{featureSolution::ControlFlowPlacementStrategy}
	//	'ControlFlowPlacementStrategy'
	//	'{' ('forAllControlFlowsIn' forAllControlFlowsIn=[repository::RepositoryComponent|EString])?
	//	'}';
	public ControlFlowPlacementStrategyElements getControlFlowPlacementStrategyAccess() {
		return pControlFlowPlacementStrategy;
	}
	
	public ParserRule getControlFlowPlacementStrategyRule() {
		return getControlFlowPlacementStrategyAccess().getRule();
	}
	
	//enum Appearance returns featureSolution::Appearance:
	//	BEFORE | AFTER | AROUND;
	public AppearanceElements getAppearanceAccess() {
		return eAppearance;
	}
	
	public EnumRule getAppearanceRule() {
		return getAppearanceAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
